services:
  go_db:
    container_name: go_db
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PORT}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: {}